FROM mcr.microsoft.com/mssql/server:2019-latest

USER root

RUN mkdir -p /usr/sqlscripts
WORKDIR /usr/sqlscripts
COPY ./sqlserver .

RUN chmod +x setup-db.sh
RUN chmod +x entrypoint.sh

USER mssql
ENTRYPOINT /bin/bash ./entrypoint.sh
